language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - composer install --dev --no-progress

matrix:
  allow_failures:
    - php: hhvm

branches:
  only:
    - develop

script: phpunit --coverage-text --configuration tests/phpunit.xml
