language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - composer install --dev --no-progress

#script: phpunit -d zend.enable_gc=0 -d date.timezone=UTC --coverage-text --configuration tests/travis/$DB.phpunit.xml

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: hhvm

branches:
  only:
    - master
